export const SPOTIFY_BASE = 'https://api.spotify.com/v1'
export const SPOTIFY_CLIENT_ID = '8a393141df824454b025a860c4ebcc86'
export const SPOTIFY_CLIENT_SECRET = 'f327dade6da44c27b0601a56b4919a19'

export const GET_ARTIST = 'GET_ARTIST'
export const GET_INPUT = 'GET_INPUT'
export const GET_ALBUMS = 'GET_ALBUMS'
export const GET_TRACKS = 'GET_TRACKS'
export const CLEAR_INPUT = 'CLEAR_INPUT'
export const FOLLOW = 'FOLLOW'
export const GET_PLAYLIST = 'GET_PLAYLIST'
